#!/usr/bin/perl
use Term::ANSIColor;
use strict;

my $cell = shift;

my $ok = 0;
my $match = 0;
my $propOk = 1;
while(<>){
  if(m/match uniquely/ig){
    $match = 1;
  }
  if(m/Property errors were found/ig){
     $propOk = 0;
  }
}

my $message = "";
if(!$match){
  $message .= " Warning: Circuits do not match\n";
}

if(!$propOk){
  $message .= " Warning: Property errors\n";
}

if(!$match || !$propOk){
  $message .= " Warning: Check log for details\n";
}

my $smiley = <<EOF;

##################################
#                _   _           #
#                *   *           #
#   CORRECT        |             #
#                \\___/           #
#                                #
##################################
EOF

my $error = <<EOF;
##################################
#                 _   _          #
#                 x   x          #
#  INCORRECT        |            #
#                  ___           #
#                                #
##################################
$message
EOF


if($match && $propOk){
  print($smiley);
}else{
  print($error);
}
